version: '3'
services:
  api:
    tty: true
    stdin_open: true
    container_name: api
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - .env
    volumes:
      - .:/var/code:rw
    depends_on:
      - postgres
    entrypoint:
      - sh
    ports:
      - '5000:5000'     
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=kareem
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
    volumes:
      - ./data/postgres:/var/lib/postgresql/data    
  redis:
    container_name: redis
    image: redis
